[package]
name = "fpe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[lib]
#crate-type = ["lib"]
#bench = false

[dependencies]
num-bigint = { version = "0.4" }
aes = "0.8.1"
